services:
  # PostgreSQL Database
  - type: postgres
    name: shoemaster-db
    plan: free
    ipAllowList: []

  # Web Service
  - type: web
    name: shoemaster-web
    plan: free
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: shoemaster-db
          property: connectionString
      - key: PORT
        value: 10000
    healthCheckPath: /api/products
    autoDeploy: true
